# resources:
# - repo: self
# queue:
#   name: Hosted VS2017

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'

steps:
- powershell: .\DoTests.ps1
  displayName: 'Invoke Tests'

trigger:
  paths:
    exclude:
    - README.md